In [272]:
import pandas as pd
import numpy as np

In [273]:
data = pd.read_csv("healthcare_dataset.csv")

In [274]:
data.shape

(55500, 15)

In [275]:
data.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [276]:
data.groupby('Name').agg(Nb=('Name', 'count')).reset_index().sort_values(['Nb'], ascending=False)

                      Name  Nb
5835           DAvId muNoZ   3
26446         allIsON cOok   2
31796          davId ADams   2
43208  mr. bRyCe gutierReZ   2
7616           ERiC NEWtOn   2
...                    ...  ..
17645        MiCHAEL EStES   1
17646       MiCHAEL MOsley   1
17647        MiCHAEL MoRSE   1
17648        MiCHAEL drAKE   1
49991         zachary WALl   1

[49992 rows x 2 columns]

In [277]:
data[data['Name'] == "DAvId muNoZ"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
2491,DAvId muNoZ,31,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive
46648,DAvId muNoZ,19,Male,A-,Cancer,2022-08-04,Jamie Gonzales,Olsen-Thomas,Blue Cross,32454.950609,406,Urgent,2022-08-17,Aspirin,Inconclusive
53672,DAvId muNoZ,28,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive

In [278]:
data_filtered = data.loc[:,['Name','Age','Gender','Blood Type']].drop_duplicates()

In [279]:
data_filtered.isna().sum()

Name          0
Age           0
Gender        0
Blood Type    0
dtype: int64

In [280]:
data[data['Name'] == "Samuel joYCe"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
6319,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive
50023,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive

# --- Notes pour data cleaning ---

1. supprimer les doublons
2. Mettre en capital la colonne "Name"
3. Arrondir à deux décimales la colonne "Billing Amount"
4. Convertir en date les colones "Date of Admission" et "Discharge Date"

# --- Notes pour structure du schéma de base de données ---

index : [Name, Date of Admission, Medical Condition]

# --- Structure de la base de données ---

[
  {
    "id": {
      "personalInfos": {
        "firstName": "firstName",
        "lastName": "lastName",
        "gender": "gender",
        "age": "age",
        "bloodType": "bloodType"
      },
      "admissions": [
        {
          "admissionId": "admissionId",
          "dateOfAdmission": "dateOfAdmission",
          "admissionType": "admissionType",
          "roomNumber": "roomNumber",
          "medicalCondition": ["medicalCondition"],
          "medication": ["medication"],
          "testResults": ["testResults"],
          "doctor": "doctor",
          "hospital": "hospital",
          "billingInfos": {
            "insuranceProvider": "insuranceProvider",
            "dischargeDate": "dischargeDate",
            "billingAmount": "billingAmount"
          }
        }
      ]
    }
  }
]

In [281]:
data['Name'] = data['Name'].str.upper()
data = data.sort_values(['Name'],ascending=True)

In [282]:
df_transformed = data.drop_duplicates()

# --- change column name ---
col_name = df_transformed.columns.to_list()
new_col_name = list(map(lambda x: x.replace(" ", "_"), col_name))
new_col_name = list(map(lambda x: x.lower(), new_col_name))
df_transformed.columns = new_col_name

# --- return name in upper case ---
df_transformed["name"] =  df_transformed["name"].str.upper()

# --- Delete title in Name
df_transformed['name_transformed'] = df_transformed['name']
df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("MRS.", "", regex=False)
df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("MR.", "", regex=False)
df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("MS.", "", regex=False)
df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("DR.", "", regex=False)
df_transformed['name_transformed'] = df_transformed['name_transformed'].str.strip()

# --- adding unique key for each patient 
df_transformed['key'] = df_transformed["name_transformed"] + "_" +  df_transformed["age"].astype(str) + "_" + df_transformed["gender"] + "_" + df_transformed["blood_type"]

/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed["name"] =  df_transformed["name"].str.upper()
/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['name_transformed'] = df_transformed['name']
/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("MRS.", "", regex=False)
/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("MR.", "", regex=False)
/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("MS.", "", regex=False)
/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['name_transformed'] = df_transformed['name_transformed'].str.replace("DR.", "", regex=False)
/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['name_transformed'] = df_transformed['name_transformed'].str.strip()
/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3540121688.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_transformed['key'] = df_transformed["name_transformed"] + "_" +  df_transformed["age"].astype(str) + "_" + df_transformed["gender"] + "_" + df_transformed["blood_type"]

In [283]:
df_transformed['key'].nunique()

54944

In [284]:
data = data.drop_duplicates()
data['key'] = data["Name"] + "_" +  data["Age"].astype(str) + "_" + data["Gender"] + "_" + data["Blood Type"]

/var/folders/gf/qtztgrtj40z_g_1rxg96hcqw0000gn/T/ipykernel_13511/3959487271.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['key'] = data["Name"] + "_" +  data["Age"].astype(str) + "_" + data["Gender"] + "_" + data["Blood Type"]

In [285]:
title = ["MRS.", "MR. ","MS. ","DR. "]
data[(~data['key'].isin(df_transformed['key'].unique())) & (data['Name'].str.slice(0,4).isin(title))]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results,key
1049,DR. AARON ANDERSEN,22,Male,A+,Cancer,2022-03-22,Kimberly Martinez,Robinson Inc,Aetna,4440.423373,245,Elective,2022-04-01,Ibuprofen,Normal,DR. AARON ANDERSEN_22_Male_A+
47710,DR. AARON PEREZ,58,Female,A-,Obesity,2021-02-28,Samuel Rosales,"Martin Walters, and Phillips",Medicare,22003.112476,276,Elective,2021-03-14,Penicillin,Abnormal,DR. AARON PEREZ_58_Female_A-
22459,DR. AARON ROBERTSON,24,Female,AB-,Obesity,2023-09-04,Miss Linda Rodriguez,"Randall, Reese and Bishop",Cigna,43424.907356,439,Urgent,2023-10-04,Penicillin,Abnormal,DR. AARON ROBERTSON_24_Female_AB-
40391,DR. ADAM ARMSTRONG,28,Female,AB-,Obesity,2020-06-06,Christina Hill,Wagner-Dixon,Medicare,15850.717653,448,Emergency,2020-06-30,Aspirin,Inconclusive,DR. ADAM ARMSTRONG_28_Female_AB-
15770,DR. ADAM CURTIS DVM,66,Female,B-,Diabetes,2023-08-08,Jeffery Johnson,"Alvarez Wilson and Fry,",Cigna,17159.420885,394,Emergency,2023-08-10,Aspirin,Inconclusive,DR. ADAM CURTIS DVM_66_Female_B-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48776,MS. TINA THOMAS,68,Female,A-,Diabetes,2019-09-24,Michael Stein,Nicholson-Jones,Cigna,21503.234479,431,Urgent,2019-09-26,Aspirin,Abnormal,MS. TINA THOMAS_68_Female_A-
23206,MS. TINA TRAN,34,Female,A+,Obesity,2023-09-27,Sandy Bell,Mann-Duncan,Blue Cross,32132.800259,371,Elective,2023-10-15,Aspirin,Normal,MS. TINA TRAN_34_Female_A+
8127,MS. VANESSA LOPEZ,34,Female,O+,Diabetes,2021-11-18,Mark Jackson,Lawson Ltd,Medicare,375.963424,217,Emergency,2021-11-27,Penicillin,Inconclusive,MS. VANESSA LOPEZ_34_Female_O+
49500,MS. VERONICA ELLIS,67,Male,B+,Cancer,2020-02-21,Robert Ramirez,Dean-Sanders,Aetna,25160.181919,223,Emergency,2020-03-22,Lipitor,Inconclusive,MS. VERONICA ELLIS_67_Male_B+
23771,MS. WANDA WYATT,45,Female,AB+,Diabetes,2019-09-21,Katrina Morse,Parks-Stone,Medicare,40962.537761,137,Emergency,2019-09-23,Aspirin,Normal,MS. WANDA WYATT_45_Female_AB+

In [286]:
df_transformed[df_transformed['name'] == "DR. AARON ANDERSEN"]

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results,name_transformed,key
1049,DR. AARON ANDERSEN,22,Male,A+,Cancer,2022-03-22,Kimberly Martinez,Robinson Inc,Aetna,4440.423373,245,Elective,2022-04-01,Ibuprofen,Normal,AARON ANDERSEN,AARON ANDERSEN_22_Male_A+

In [287]:
#~data['key'].isin(df_transformed['key'].unique())) &

In [287]:
#~data['key'].isin(df_transformed['key'].unique())) &