In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("healthcare_dataset.csv")

In [33]:
data.shape

(55500, 15)

In [34]:
data.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [35]:
data.groupby('Name').agg(Nb=('Name', 'count')).reset_index().sort_values(['Nb'], ascending=False)

                      Name  Nb
5835           DAvId muNoZ   3
26446         allIsON cOok   2
31796          davId ADams   2
43208  mr. bRyCe gutierReZ   2
7616           ERiC NEWtOn   2
...                    ...  ..
17645        MiCHAEL EStES   1
17646       MiCHAEL MOsley   1
17647        MiCHAEL MoRSE   1
17648        MiCHAEL drAKE   1
49991         zachary WALl   1

[49992 rows x 2 columns]

In [36]:
data[data['Name'] == "DAvId muNoZ"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
2491,DAvId muNoZ,31,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive
46648,DAvId muNoZ,19,Male,A-,Cancer,2022-08-04,Jamie Gonzales,Olsen-Thomas,Blue Cross,32454.950609,406,Urgent,2022-08-17,Aspirin,Inconclusive
53672,DAvId muNoZ,28,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive

In [37]:
data_filtered = data.loc[:,['Name','Age','Gender','Blood Type']]

In [38]:
data_filtered[data_filtered.duplicated()]

                     Name  Age  Gender Blood Type
50023        Samuel joYCe   56    Male         O+
50040    KIMBErly vasqueZ   26    Male         A-
50055      SCoTT tHOrNton   55  Female         B-
50070         wiLliam LEe   27  Female         O+
50078  chRistOPheR NoRrIs   38    Male        AB-
...                   ...  ...     ...        ...
55461      connOR coMPTon   63    Male         A+
55462       alYSsA mIlLER   35  Female         A-
55464        ChRIs huGHeS   35  Female        AB-
55484     keNNEtH alvarez   80    Male         O+
55491       lInDA grIFfin   47  Female         O+

[534 rows x 4 columns]

In [39]:
data[data['Name'] == "Samuel joYCe"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
6319,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive
50023,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive

# --- Notes pour data cleaning ---

1. supprimer les doublons
2. Mettre en capital la colonne "Name"
3. Arrondir à deux décimales la colonne "Billing Amount"
4. Convertir en date les colones "Date of Admission" et "Discharge Date"

# --- Notes pour structure du schéma de base de données ---

index : [Name, Date of Admission, Medical Condition]

# --- Structure de la base de données ---

[
  {
    "id": {
      "personalInfos": {
        "firstName": "firstName",
        "lastName": "lastName",
        "gender": "gender",
        "age": "age",
        "bloodType": "bloodType"
      },
      "admissions": [
        {
          "admissionId": "admissionId",
          "dateOfAdmission": "dateOfAdmission",
          "admissionType": "admissionType",
          "roomNumber": "roomNumber",
          "medicalCondition": ["medicalCondition"],
          "medication": ["medication"],
          "testResults": ["testResults"],
          "doctor": "doctor",
          "hospital": "hospital",
          "billingInfos": {
            "insuranceProvider": "insuranceProvider",
            "dischargeDate": "dischargeDate",
            "billingAmount": "billingAmount"
          }
        }
      ]
    }
  }
]