In [32]:
import pandas as pd
import numpy as np

In [33]:
data = pd.read_csv("healthcare_dataset.csv")

In [34]:
data.head(5)

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [35]:
data.shape

(55500, 15)

In [36]:
data.dtypes

Name                   object
Age                     int64
Gender                 object
Blood Type             object
Medical Condition      object
Date of Admission      object
Doctor                 object
Hospital               object
Insurance Provider     object
Billing Amount        float64
Room Number             int64
Admission Type         object
Discharge Date         object
Medication             object
Test Results           object
dtype: object

In [37]:
data.groupby('Name').agg(Nb=('Name', 'count')).reset_index().sort_values(['Nb'], ascending=False)

                      Name  Nb
5835           DAvId muNoZ   3
26446         allIsON cOok   2
31796          davId ADams   2
43208  mr. bRyCe gutierReZ   2
7616           ERiC NEWtOn   2
...                    ...  ..
17645        MiCHAEL EStES   1
17646       MiCHAEL MOsley   1
17647        MiCHAEL MoRSE   1
17648        MiCHAEL drAKE   1
49991         zachary WALl   1

[49992 rows x 2 columns]

In [38]:
data[data['Name'] == "DAvId muNoZ"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
2491,DAvId muNoZ,31,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive
46648,DAvId muNoZ,19,Male,A-,Cancer,2022-08-04,Jamie Gonzales,Olsen-Thomas,Blue Cross,32454.950609,406,Urgent,2022-08-17,Aspirin,Inconclusive
53672,DAvId muNoZ,28,Male,AB+,Diabetes,2022-12-20,Maurice Davis,Wall-Weaver,Medicare,25773.328236,406,Elective,2023-01-09,Penicillin,Inconclusive

In [39]:
data_filtered = data.loc[:,['Name','Age','Gender','Blood Type']]

In [40]:
data_filtered[data_filtered.duplicated()]

                     Name  Age  Gender Blood Type
50023        Samuel joYCe   56    Male         O+
50040    KIMBErly vasqueZ   26    Male         A-
50055      SCoTT tHOrNton   55  Female         B-
50070         wiLliam LEe   27  Female         O+
50078  chRistOPheR NoRrIs   38    Male        AB-
...                   ...  ...     ...        ...
55461      connOR coMPTon   63    Male         A+
55462       alYSsA mIlLER   35  Female         A-
55464        ChRIs huGHeS   35  Female        AB-
55484     keNNEtH alvarez   80    Male         O+
55491       lInDA grIFfin   47  Female         O+

[534 rows x 4 columns]

In [41]:
data[data['Name'] == "Samuel joYCe"]

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
6319,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive
50023,Samuel joYCe,56,Male,O+,Arthritis,2022-11-03,Krista Hartman,Thomas-Ballard,UnitedHealthcare,15654.830587,157,Urgent,2022-11-22,Aspirin,Inconclusive

In [42]:
data = data.drop_duplicates()

# --- Notes pour data cleaning ---

1. supprimer les doublons
2. Mettre en capital la colonne "Name"
3. Arrondir à deux décimales la colonne "Billing Amount"
4. Convertir en date les colones "Date of Admission" et "Discharge Date"

# --- Notes pour structure du schéma de base de données ---

index : [Name, Date of Admission, Medical Condition]

# --- Structure de la base de données ---

[
  {
    "id": {
      "personalInfos": {
        "firstName": "firstName",
        "lastName": "lastName",
        "gender": "gender",
        "age": "age",
        "bloodType": "bloodType"
      },
      "admissions": [
        {
          "admissionId": "admissionId",
          "dateOfAdmission": "dateOfAdmission",
          "admissionType": "admissionType",
          "roomNumber": "roomNumber",
          "medicalCondition": ["medicalCondition"],
          "medication": ["medication"],
          "testResults": ["testResults"],
          "doctor": "doctor",
          "hospital": "hospital",
          "billingInfos": {
            "insuranceProvider": "insuranceProvider",
            "dischargeDate": "dischargeDate",
            "billingAmount": "billingAmount"
          }
        }
      ]
    }
  }
]

In [46]:
data_head_5 = data.head(5)

In [74]:
data_head_5

{'name': {0: 'Bobby JacksOn',
  1: 'LesLie TErRy',
  2: 'DaNnY sMitH',
  3: 'andrEw waTtS',
  4: 'adrIENNE bEll'},
 'age': {0: 30, 1: 62, 2: 76, 3: 28, 4: 43},
 'gender': {0: 'Male', 1: 'Male', 2: 'Female', 3: 'Female', 4: 'Female'},
 'blood type': {0: 'B-', 1: 'A+', 2: 'A-', 3: 'O+', 4: 'AB+'},
 'medical condition': {0: 'Cancer',
  1: 'Obesity',
  2: 'Obesity',
  3: 'Diabetes',
  4: 'Cancer'},
 'date of admission': {0: '2024-01-31',
  1: '2019-08-20',
  2: '2022-09-22',
  3: '2020-11-18',
  4: '2022-09-19'},
 'doctor': {0: 'Matthew Smith',
  1: 'Samantha Davies',
  2: 'Tiffany Mitchell',
  3: 'Kevin Wells',
  4: 'Kathleen Hanna'},
 'hospital': {0: 'Sons and Miller',
  1: 'Kim Inc',
  2: 'Cook PLC',
  3: 'Hernandez Rogers and Vang,',
  4: 'White-White'},
 'insurance provider': {0: 'Blue Cross',
  1: 'Medicare',
  2: 'Aetna',
  3: 'Medicare',
  4: 'Aetna'},
 'billing amount': {0: 18856.281305978155,
  1: 33643.327286577885,
  2: 27955.096078842456,
  3: 37909.78240987528,
  4: 14238.317813937623},
 'room number': {0: 328, 1: 265, 2: 205, 3: 450, 4: 458},
 'admission type': {0: 'Urgent',
  1: 'Emergency',
  2: 'Emergency',
  3: 'Elective',
  4: 'Urgent'},
 'discharge date': {0: '2024-02-02',
  1: '2019-08-26',
  2: '2022-10-07',
  3: '2020-12-18',
  4: '2022-10-09'},
 'medication': {0: 'Paracetamol',
  1: 'Ibuprofen',
  2: 'Aspirin',
  3: 'Ibuprofen',
  4: 'Penicillin'},
 'test results': {0: 'Normal',
  1: 'Inconclusive',
  2: 'Normal',
  3: 'Abnormal',
  4: 'Abnormal'},
 'admission_id': {0: 1, 1: 1, 2: 1, 3: 1, 4: 1}}

In [78]:
exemple = [[1], [2], [3]]

In [83]:
[number for sublist in exemple for number in sublist]

SyntaxError: invalid syntax (52454820.py, line 1)

In [88]:
for _, row in data_head_5.iterrows():
    print(row)

name                    Bobby JacksOn
age                                30
gender                           Male
blood type                         B-
medical condition              Cancer
date of admission          2024-01-31
doctor                  Matthew Smith
hospital              Sons and Miller
insurance provider         Blue Cross
billing amount           18856.281306
room number                       328
admission type                 Urgent
discharge date             2024-02-02
medication                Paracetamol
test results                   Normal
admission_id                        1
Name: 0, dtype: object
name                     LesLie TErRy
age                                62
gender                           Male
blood type                         A+
medical condition             Obesity
date of admission          2019-08-20
doctor                Samantha Davies
hospital                      Kim Inc
insurance provider           Medicare
billing amount           33643.327287
room number                       265
admission type              Emergency
discharge date             2019-08-26
medication                  Ibuprofen
test results             Inconclusive
admission_id                        1
Name: 1, dtype: object
name                       DaNnY sMitH
age                                 76
gender                          Female
blood type                          A-
medical condition              Obesity
date of admission           2022-09-22
doctor                Tiffany Mitchell
hospital                      Cook PLC
insurance provider               Aetna
billing amount            27955.096079
room number                        205
admission type               Emergency
discharge date              2022-10-07
medication                     Aspirin
test results                    Normal
admission_id                         1
Name: 2, dtype: object
name                                andrEw waTtS
age                                           28
gender                                    Female
blood type                                    O+
medical condition                       Diabetes
date of admission                     2020-11-18
doctor                               Kevin Wells
hospital              Hernandez Rogers and Vang,
insurance provider                      Medicare
billing amount                       37909.78241
room number                                  450
admission type                          Elective
discharge date                        2020-12-18
medication                             Ibuprofen
test results                            Abnormal
admission_id                                   1
Name: 3, dtype: object
name                   adrIENNE bEll
age                               43
gender                        Female
blood type                       AB+
medical condition             Cancer
date of admission         2022-09-19
doctor                Kathleen Hanna
hospital                 White-White
insurance provider             Aetna
billing amount          14238.317814
room number                      458
admission type                Urgent
discharge date            2022-10-09
medication                Penicillin
test results                Abnormal
admission_id                       1
Name: 4, dtype: object